{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}

module LDAP.Schema.AttributeTypes where

import LDAP.Schema.Util

makeAttributeType "AliasedObjectName" "aliasedObjectName"
makeAttributeType "AuthorityRevocationList" "authorityRevocationList"
makeAttributeType "BusinessCategory" "businessCategory"
makeAttributeType "CountryName" "c"
makeAttributeType "CACertificate" "cACertificate"
makeAttributeType "CertificateRevocationList" "certificateRevocationList"
makeAttributeType "CommonName" "cn"
makeAttributeType "CrossCertificatePair" "crossCertificatePair"
makeAttributeType "DeltaRevocationList" "deltaRevocationList"
makeAttributeType "Description" "description"
makeAttributeType "DestinationIndicator" "destinationIndicator"
makeAttributeType "DmdName" "dmdName"
makeAttributeType "DnQualifier" "dnQualifier"
makeAttributeType "DomainComponent" "dc"
makeAttributeType "EnhancedSearchGuide" "enhancedSearchGuide"
makeAttributeType "FacsimileTelephoneNumber" "facsimileTelephoneNumber"
makeAttributeType "GenerationQualifier" "generationQualifier"
makeAttributeType "GivenName" "givenName"
makeAttributeType "HouseIdentifier" "houseIdentifier"
makeAttributeType "Initials" "initials"
makeAttributeType "InternationaliSDNNumber" "internationaliSDNNumber"
makeAttributeType "KnowledgeInformation" "knowledgeInformation"
makeAttributeType "LocalityName" "l"
makeAttributeType "Member" "member"
makeAttributeType "Name" "name"
makeAttributeType "OrganizationName" "o"
makeAttributeType "OrganizationalUnitName" "ou"
makeAttributeType "Owner" "owner"
makeAttributeType "PhysicalDeliveryOfficeName" "physicalDeliveryOfficeName"
makeAttributeType "PostOfficeBox" "postOfficeBox"
makeAttributeType "PostalAddress" "postalAddress"
makeAttributeType "PostalCode" "postalCode"
makeAttributeType "PreferredDeliveryMethod" "preferredDeliveryMethod"
makeAttributeType "PresentationAddress" "presentationAddress"
makeAttributeType "ProtocolInformation" "protocolInformation"
makeAttributeType "RegisteredAddress" "registeredAddress"
makeAttributeType "RoleOccupant" "roleOccupant"
makeAttributeType "SearchGuide" "searchGuide"
makeAttributeType "SeeAlso" "seeAlso"
makeAttributeType "SerialNumber" "serialNumber"
makeAttributeType "State" "st"
makeAttributeType "Street" "street"
makeAttributeType "SupportedAlgorithms" "supportedAlgorithms"
makeAttributeType "SupportedApplicationContext" "supportedApplicationContext"
makeAttributeType "Surname" "sn"
makeAttributeType "TelephoneNumber" "telephoneNumber"
makeAttributeType "TeletextTerminalIdentifier" "teletextTerminalIdentifier"
makeAttributeType "TelexNumber" "telexNumber"
makeAttributeType "Title" "title"
makeAttributeType "UniqueMember" "uniqueMember"
makeAttributeType "UserCertificate" "userCertificate"
makeAttributeType "UserPassword" "userPassword"
makeAttributeType "X121Address" "x121Address"
makeAttributeType "X500UniqueIdentifier" "x500UniqueIdentifier"
