name: LDAP
version: 0.0.1

dependencies:
  - base
  - binary
  - binary-parsers
  - bytestring
  - lens
  - text
  - template-haskell
  - utf8-string

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  dependencies: LDAP

tests:
  ldap-tests:
    main: Main.hs
    source-dirs: test
    dependencies:
      - LDAP
      - QuickCheck
      - quickcheck-instances
      - hspec

ghc-options:
 - -ddump-splices
 - -ddump-to-file
 - -dth-dec-file
